name: "🕷️ Bug Report"
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter the description
      placeholder: Description of the bug / unwanted behaviour...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter the reproduction steps
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots / Screen Recordings"
      description: If applicable, add screenshots / screen recordings to help explain the bug.
      value: |
        Paste, drag and drop, or click option below to add your files here.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What type of Operating System are you seeing the problem on ?
      multiple: true
      options:
        - iOS
        - Android
    validations:
      required: true
  - type: dropdown
    id: triage
    attributes:
      label: "According to you how serious is the problem"
      description: Bug triage level
      multiple: false
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true
